{{- if (.Values.global.use_rbac) -}}
{{- if (.Capabilities.APIVersions.Has (include "rbacAPIVersion" .)) -}}
kind: ClusterRole
apiVersion: {{ template "rbacAPIVersion" . }}
metadata:
  name: drycc:drycc-logger-fluentd
  labels:
    app: drycc-logger-fluentd
    heritage: drycc
rules:
- apiGroups: [""]
  resources: ["pods", "namespaces"]
  verbs: ["list", "get", "watch"]
{{- end -}}
{{- end -}}
