apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: drycc-logger-fluentd
  namespace: drycc
  labels:
    heritage: drycc
spec:
  selector:
    matchLabels:
      app: drycc-logger-fluentd
      heritage: drycc
  template:
    metadata:
      name: drycc-logger-fluentd
      labels:
        heritage: drycc
        app: drycc-logger-fluentd
    spec:
      serviceAccount: drycc-logger-fluentd
      containers:
      - name: drycc-logger-fluentd
        image: drycc/fluentd:canary
        imagePullPolicy: Always
        volumeMounts:
        - name: varlog
          mountPath: /var/log
        - name: varlibdockercontainers
          mountPath: /var/lib/docker/containers
          readOnly: true
        env:
        - name: DEBUG
          value: "true"
      volumes:
      - name: varlog
        hostPath:
          path: /var/log
      - name: varlibdockercontainers
        hostPath:
          path: /var/lib/docker/containers
