imageOrg: "drycc"
imagePullPolicy: "Always"
imageTag: "canary"
imageRegistry: "docker.io"
# limitsCpu: "100m"
# limitsMemory: "50Mi"

redis:
  replicas: 1
# external syslog endpoint
syslog:
  host: "" # external syslog endpoint url
  port: "" # external syslog endpoint port

sources:
  startScript: false
  docker: false
  etcd: false
  kubelet: false
  kubeApi: false
  controller: false
  scheduler: false

output:
  disableDrycc: false

boot:
  installBuildTools: false

# Any custom fluentd environment variables (https://github.com/drycc/fluentd#configuration)
# can be specified as key-value pairs under daemonEnvironment.
daemonEnvironment:
  CONTAINER_TAIL_PARSER_TYPE: json

# Role-Based Access Control for Kubernetes >= 1.5
global:
  rbac: false
  clusterDomain: "cluster.local"
